export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_FOLLOW = "USER_FOLLOW";
export const USER_UNFOLLOW = "USER_UNFOLLOW";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
